federation_version: 2
subgraphs:
  users:
    routing_url: http://localhost:4000/
    schema:
      file: graphs/users.graphql
  reviews:
    routing_url: http://localhost:4002/
    schema:
      file: graphs/accounts.graphql
