federation_version: 2
subgraphs:
  common:
    routing_url: http://localhost:4000/
    schema:
      file: graphs/accounts/common/schema.graphql
  tokens:
    routing_url: http://localhost:4002/
    schema:
      file: graphs/accounts/tokens/schema.graphql
  business:
    routing_url: http://localhost:4004/
    schema:
      file: graphs/accounts/business/schema.graphql
  main:
    routing_url: http://localhost:4006/
    schema:
      file: graphs/accounts/main/schema.graphql
